### ISSUE TITLE
Collaberation on parallel flux with xDiT

### ISSUE THREAD

**Issue by feifeibear** [chengzeyi/piflux#1]
Hello, I found this repo name very attractive.

xDiT also supports parallel inference for Flux.
https://github.com/xdit-project/xDiT

Can we work on this topic together?

**Comment by chengzeyi** [comment]
> Hello, I found this repo name very attractive.
> 
> 
> 
> xDiT also supports parallel inference for Flux.
> 
> https://github.com/xdit-project/xDiT
> 
> 
> 
> Can we work on this topic together?

Aha, we can talk on WeChat. My account is ichengzeyi. It's very exciting to know that we all see the promising future of the need of parallelism for media generation.

**Comment by feifeibear** [comment]
I have already sent the invitation.
xDiT has supported sequence parallel for flux, but the performance still needs to improve. We can work on this togetherr.

https://github.com/xdit-project/xDiT/pull/168
