### ISSUE TITLE
output wrong on 4 GPUs

### ISSUE THREAD

**Issue by feifeibear** [chengzeyi/piflux#3]
@chengzeyi Wonderful job!
However, I find the output on 4 GPUs is incorrect. 

here is my script:

```
torchrun --nproc_per_node=$N_GPUS examples/run_flux.py --warmups 1 --seed 123
```

<img width="959" alt="image" src="https://github.com/user-attachments/assets/ecf34284-8fb8-45a0-a920-b61b47d666bd">

**Comment by chengzeyi** [comment]
should be fixed in the latest commit
