### ISSUE TITLE
4 GPUs output is still not correct.

### ISSUE THREAD

**Issue by feifeibear** [chengzeyi/piflux#4]
<img width="651" alt="image" src="https://github.com/user-attachments/assets/7bc26e94-f223-434b-be19-3de2671499a7">

**Comment by chengzeyi** [comment]
Tested on 4 RTXA6000 GPUs with torch 2.5.0, the output seems to be reasonable.
![image](https://github.com/user-attachments/assets/cfd9798a-182d-4e31-a63a-de793ded7ea6)
